#!/bin/bash
yum install -y wget unzip rubygem-bundler httpd


cat >/usr/lib/systemd/system/myapp.service <<EOL
[Unit]
Description=MyApp
Requires=network.target

[Service]
Type=simple
User=webuser
Group=webuser
WorkingDirectory=/home/webuser/simple-sinatra-app-master
ExecStart=/usr/bin/bash -lc 'bundle exec rackup --port 8080'
TimeoutSec=30
RestartSec=15s
Restart=always

[Install]
WantedBy=multi-user.target

EOL

cat >/etc/httpd/conf.d/proxy.conf <<EOL
<VirtualHost *:*>
    ProxyPreserveHost On
    ProxyPass        "/" "http://localhost:8080/"
    ProxyPassReverse "/" "http://localhost:8080/"
</VirtualHost>

EOL


setsebool -P httpd_can_network_connect on


systemctl enable myapp.service

su - webuser <<'EOF'

#rm -f master.zip
#rm -fr simple-sinatra-app-master

#wget https://github.com/rea-cruitment/simple-sinatra-app/archive/master.zip

#unzip master.zip
cd simple-sinatra-app-master/

bundle install
EOF






