#!/bin/bash
#install packages needed to run app and debug
yum install -y wget unzip rubygem-bundler httpd links

# create systemctl file
cat >/usr/lib/systemd/system/myapp.service <<EOL
[Unit]
Description=MyApp
Requires=network.target

[Service]
Type=simple
User=webuser
Group=webuser
WorkingDirectory=/home/webuser/simple-sinatra-app-master
ExecStart=/usr/bin/bash -lc 'bundle exec rackup --port 8080'
TimeoutSec=30
RestartSec=15s
Restart=always

[Install]
WantedBy=multi-user.target

EOL

#create apache proxy file
cat >/etc/httpd/conf.d/proxy.conf <<EOL
<VirtualHost *:*>
    ProxyPreserveHost On
    ProxyPass        "/" "http://localhost:8080/"
    ProxyPassReverse "/" "http://localhost:8080/"
</VirtualHost>

EOL

# allow apache to proxy app by changing selinux
/sbin/setsebool -P httpd_can_network_connect on

# enable this new service
systemctl enable myapp.service








