#!/bin/bash

chown -R webuser:webuser /home/webuser/simple-sinatra-app-master

su - webuser <<'EOF'
cd simple-sinatra-app-master/

bundle install
EOF

systemctl start myapp.service
systemctl start httpd


