#!/bin/bash
isExistApp = `pgrep ruby`
if [[ -n  $isExistApp ]]; then
    systemctl stop myapp.service        
fi

isExistApp = `pgrep httpd`
if [[ -n  $isExistApp ]]; then
    systemctl stop httpd.service        
fi

